- name: Find V5 project
  run: |
    ZIP=$(find . -maxdepth 2 -type f -name "jadwal-drosey-v5-*.zip" | head -n 1)
    echo "Using project: $ZIP"
    test -n "$ZIP"

- name: Extract V5
  run: |
    ZIP=$(find . -maxdepth 2 -type f -name "jadwal-drosey-v5-*.zip" | head -n 1)
    mkdir android-project
    unzip -q "$ZIP" -d android-project
    - name: Find V7 project
  run: |
    ZIP=$(find . -maxdepth 2 -type f -name "jadwal-drosey-v7-*.zip" | head -n 1)
    echo "Using project: $ZIP"
    test -n "$ZIP"

- name: Extract V7
  run: |
    ZIP=$(find . -maxdepth 2 -type f -name "jadwal-drosey-v7-*.zip" | head -n 1)
    mkdir android-project
    unzip -q "$ZIP" -d android-project
